export const productsList = [
  {
    name: 'Wholesome Dog Food',
    description: 'Nutritious and balanced kibble for adult dogs.',
    price: 29.99,
    image: 'products/dog-food.jpg',
    stripePriceId: 'price_xxxxx_dogfood',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Plush Squeaky Toy',
    description: 'Durable and fun plush toy for dogs of all sizes.',
    price: 12.99,
    image: 'products/squeaky-toy.jpg',
    stripePriceId: 'price_xxxxx_toy',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Catnip Cat Toy',
    description: 'Organic catnip filled toy for playful cats.',
    price: 5.99,
    image: 'products/catnip-cat-toy.jpg',
    stripePriceId: 'price_xxxxx_catnip',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Comfortable Cat Bed',
    description: 'Soft and cozy bed for a purrfect nap.',
    price: 19.99,
    image: 'products/cat-bed.jpg',
    stripePriceId: 'price_xxxxx_catbed',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Aquarium Starter Kit',
    description: 'Everything you need to set up a freshwater aquarium.',
    price: 49.99,
    image: 'products/aquarium-kit.jpg',
    stripePriceId: 'price_xxxxx_aquarium',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Bird Cage with Stand',
    description: 'Spacious cage for small to medium-sized birds.',
    price: 79.99,
    image: 'products/bird-cage.jpg',
    stripePriceId: 'price_xxxxx_birdcage',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Hamster Wheel',
    description: 'Silent exercise wheel for hamsters.',
    price: 8.99,
    image: 'products/hamster-wheel.jpg',
    stripePriceId: 'price_xxxxx_wheel',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Reptile Terrarium',
    description: 'Glass terrarium for reptiles and amphibians.',
    price: 59.99,
    image: 'products/reptire-terrarium.jpg',
    stripePriceId: 'price_xxxxx_terrarium',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Fish Food Flakes',
    description: 'Nutritious flakes for a variety of fish.',
    price: 6.99,
    image: 'products/fish-food-flakes.jpg',
    stripePriceId: 'price_xxxxx_fishfood',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Dog Leash and Collar',
    description: 'Durable leash and collar set for daily walks.',
    price: 24.99,
    image: 'products/dog-leash.jpg',
    stripePriceId: 'price_xxxxx_leash',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Cat Scratching Post',
    description: 'Tall scratching post with dangling toys.',
    price: 39.99,
    image: 'products/cat-scratch-post.jpg',
    stripePriceId: 'price_xxxxx_scratch',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Small Animal Cage',
    description: 'Cage suitable for rabbits, guinea pigs, or ferrets.',
    price: 69.99,
    image: 'products/small-anim-cage.jpg',
    stripePriceId: 'price_xxxxx_smallcage',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Bird Seed Mix',
    description: 'A blend of seeds for various bird species.',
    price: 12.99,
    image: 'products/bird-seed-mix.jpg',
    stripePriceId: 'price_xxxxx_seed',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Reptile Heating Pad',
    description: 'Provides warmth for reptiles.',
    price: 19.99,
    image: 'products/reptile-heating-pad.jpg',
    stripePriceId: 'price_xxxxx_heatpad',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Aquarium Filter',
    description: 'Keeps aquarium water clean and clear.',
    price: 29.99,
    image: 'products/aquarium-filter.jpg',
    stripePriceId: 'price_xxxxx_filter',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Dog Treats',
    description: 'Tasty and healthy treats for dogs.',
    price: 9.99,
    image: 'products/dog-treats.jpg',
    stripePriceId: 'price_xxxxx_treats',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Cat Grooming Brush',
    description: 'Removes loose hair and prevents mats.',
    price: 14.99,
    image: 'products/cat-grooming-brush.jpg',
    stripePriceId: 'price_xxxxx_brush',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Small Animal Bedding',
    description: 'Soft and absorbent bedding for small pets.',
    price: 7.99,
    image: 'products/small-animal-bedding.jpg',
    stripePriceId: 'price_xxxxx_bedding',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Bird Toys',
    description: 'Assortment of toys to keep birds entertained.',
    price: 15.99,
    image: 'products/bird-toys.jpg',
    stripePriceId: 'price_xxxxx_birdtoys',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Reptile Food',
    description: 'Nutritious food for various reptile species.',
    price: 11.99,
    image: 'products/reptile-food.jpg',
    stripePriceId: 'price_xxxxx_repfood',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
];
